skipubootdownload=1
imgfile=bpi-r3_emmc.img.gz
kernelfile=bpi-r3_6.12.47-main.tar.gz
userpackages="ethtool iperf3 tcpdump git tig mtd-utils memtester file pciutils usbutils traceroute iperf3 net-tools psmisc wget curl fdisk ack bridge-utils wpasupplicant isc-dhcp-client man tshark"
